export const GET_CLOTHS_DATA_REQUEST: string = "GET_CLOTHS_DATA_REQUEST";
export const GET_CLOTHS_DATA_SUCCESS: string = "GET_CLOTHS_DATA_SUCCESS";
export const GET_CLOTHS_DATA_FAILURE: string = "GET_CLOTHS_DATA_FAILURE";

export const GET_CARTKEY_REQUEST: string = "GET_CARTKEY_REQUEST";

export const GET_CARTKEY_SUCCESS: string = "GET_CARTKEY_SUCCESS";

export const GET_CARTKEY_FAILURE: string = "GET_CARTKEY_FAILURE";

export const GET_CARTDATA_REQUEST: string = "GET_CARTDATA_REQUEST";

export const GET_CARTDATA_SUCCESS: string = "GET_CARTDATA_SUCCESS";

export const GET_CARTDATA_FAILURE: string = "GET_CARTDATA_FAILURE";

export const GET_DATA_LENGTH: string = "GET_DATA_LENGTH";
